string interpolation instead of composite formatting
indexes were missing in String.Format(). Suggesting changing uri to interpolated string.
```
System.FormatException: Input string was not in a correct format.
   at System.Text.StringBuilder.FormatError()
   at System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.Format(String format, Object arg0)
   at provide.Vault.ListVaultKeys(String token, String vaultID, Dictionary`2 args)
```